# Generated by Django 5.1.6 on 2026-04-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('capacity', models.FloatField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_TRANSIT', 'In Transit'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
            ],
        ),
    ]
